### ISSUE TITLE
Question: How is the RangeSlicer different to a Scaled value?

### ISSUE THREAD

**Issue by mmartinortiz** [CedarGroveStudios/Cedargrove_CircuitPython_RangeSlicer#5]
Hi,

After I heard you at the [CircuitPython podcast](https://www.circuitpythonshow.com/@circuitpythonshow/episodes/jan-goolsbey) talking about this library, and it got me thinking about a little project of mine. I'm tinkering with an old [Wheel controller from the 90s](https://github.com/mmartinortiz/pico-speed-wheel)—just a couple of potentiometers and a bunch of buttons. When I first tackled the project, I [scaled the potentiometer](https://github.com/mmartinortiz/pico-speed-wheel/blob/main/code.py#L80) values between -127 and 127 based on their min and max readings. But, just like you mentioned in the podcast, the potentiometer noise started messing with my values.

I've been playing around with the library for a few days now. To get a handle on things, I collected data on registered values for 50 reads without touching the potentiometer. Check out the results below:

- `slice`: Value of the `slice` argument.
- `hyst`: Value of the `hyst` argument
- `avg_slicer`: Average value returned by the `range_slicer` method.
- `avg_scaled`: Average value resulted of directly scaling the potentiometer value
- `avg_slicer_diff`: Average absolute difference between two consecutive values returned by the `range_slicer` method
- `avg_scaled_diff`: Average absolute difference between two consecutive scaled values

|    |   slice |   hyst |   avg_slicer |   avg_scaled |   avg_slicer_diff |   avg_scaled_diff |
|---:|--------:|-------:|-------------:|-------------:|------------------:|------------------:|
|  0 |       1 |   0.15 |        13.6  |        12.88 |              0.76 |              1.24 |
|  1 |       1 |   0.25 |        13.5  |        12.88 |              0.84 |              1.34 |
|  2 |       1 |   0.5  |        13.38 |        13.08 |              0.78 |              1.2  |
|  3 |       1 |   1    |        13.7  |        13.02 |              0.8  |              1.12 |
|  4 |       1 |   2    |        14.7  |        12.88 |              0.7  |              1.2  |
|  5 |       1 |   4    |        16.6  |        13    |              0.92 |              1.28 |
|  6 |       1 |   8    |        20.54 |        13.06 |              0.96 |              1    |
|  7 |       2 |   0.15 |        14    |        12.86 |              1.1  |              0.98 |
|  8 |       2 |   0.25 |        13.12 |        12.82 |              0.58 |              1.08 |
|  9 |       2 |   0.5  |        12.8  |        12.88 |              0.54 |              1.12 |
| 10 |       2 |   1    |        14.08 |        12.94 |              1.34 |              1.02 |
| 11 |       2 |   2    |        16    |        12.86 |              1.18 |              1.18 |
| 12 |       2 |   4    |        20.04 |        12.9  |              1.38 |              1.14 |
| 13 |       2 |   8    |        27.68 |        12.9  |              1.58 |              1.08 |
| 14 |       4 |   0.15 |        13    |        12.74 |              0.26 |              1.1  |
| 15 |       4 |   0.25 |        13    |        12.82 |              0.26 |              1.22 |
| 16 |       4 |   0.5  |        12.68 |        12.8  |              0.74 |              1.22 |
| 17 |       4 |   1    |        13    |        12.8  |              0.26 |              1.28 |
| 18 |       4 |   2    |        17    |        12.96 |              0.34 |              1.12 |
| 19 |       4 |   4    |        25    |        12.98 |              0.5  |              1    |
| 20 |       4 |   8    |        41    |        12.78 |              0.82 |              1.32 |
| 21 |       8 |   0.15 |        11.72 |        12.88 |              3.54 |              1.14 |
| 22 |       8 |   0.25 |         9    |        13    |              0.18 |              1.32 |
| 23 |       8 |   0.5  |         9    |        12.84 |              0.18 |              1.08 |
| 24 |       8 |   1    |        17    |        12.84 |              0.34 |              1.28 |
| 25 |       8 |   2    |        24.84 |        12.96 |              0.66 |              1.32 |
| 26 |       8 |   4    |        40.52 |        12.78 |              1.62 |              1.08 |
| 27 |       8 |   8    |        72.68 |        13.2  |              2.1  |              0.78 |

Looking to the data, I get the following conclusions:
1. The value of `slice` changes the output value scale without an impact in the noise.
2. The hyst value plays a bigger role in the sliced value. Values below 1 get me results closer to a regular scale.
3. `RangeSlicer` produces less noise.
4. There is not direct relation between values of `slice` and `hyst`, and the noise produced.

When do you think it's smarter to go with RangeSlicer instead of the usual scaling method or a filter? Would you have some tips for selecting a good `slice` and `hyst`?

[data.csv](https://github.com/CedarGroveStudios/CircuitPython_RangeSlicer/files/13772611/data.csv)

Best,
Manuel

**Comment by CedarGroveStudios** [comment]
Hello Manuel,

Looks like you are certainly doing your homework analyzing how RangeSlicer can work for your project. I appreciate your comments and attention to detail.

The general approach to using RangeSlicer is first to adjust the input and output minimums and maximums to meet the needs of your project. For potentiometers, the input values should represent the raw values of the potentiometer -- that are seldom the minimum and maximum values of the ADC. The input minimum is usually around 100 to 2000; the maximum is similarly less than full scale, sometimes significantly.

The next step is to select an output range. This one can range from 0 to a maximum value like 127 for MIDI control codes. RangeSlicer will map the output range to the input range just like the CircuitPython version of `simpleio.map_range`.
In most cases, a step value of 1.0 will match the output range resolution. Setting the index type to `out_integer=True` will limit the output value to just integers, handy for MIDI control codes.

Finally, set the hysteresis factor to a value that is equivalent to the noise level of a slice. I've found that for most potentiometers, the default value of 0.1 (10%) usually works. Of course that's when the output range is much smaller than the input range. When the input and output ranges are the same, hysteresis may need to increase to 0.5 (50%) of a slice value. For my projects so far, the hysteresis value hasn't had to exceed 0.25 (25% of a slice).

RangeSlicer will accept hysteresis values above 1.0 (100%), but the output becomes somewhat unpredictable.

In one project, RangeSlicer was used to simulate a 6-detent rotary switch using a potentiometer. The instantiation looked something like this:

`rs = RangeSlicer(in_min=200, in_max=64000, out_min=0, out_max= 5, out_slice=1, hyst_factor=0.2, out_integer=True)`

Once instantiated with parameters that match your project, RangeSlicer properties shouldn't need to be changed. How are you setting it up in your project code?

As far as selecting to use RangeSlicer or filtering (averaging) or another noise squelching method, it depends on your project. If responsiveness is important, then you may want to avoid filtering as it takes time to read values and calculate the average, especially if you are averaging a large number of input samples in order to smooth the noise out of the signal. The benefit of filtering, however, is that it can make the control "feel" smoother.

Hope this information helps and that the level of detail is appropriate. Let me how it works out for your project. If you have other questions, feel free to ask.

-- Jan

**Comment by mmartinortiz** [comment]
Hi Jan,

Thanks for your extensive answer, I really appreciate the time you are taking.

> For potentiometers, the input values should represent the raw values of the potentiometer -- that are seldom the minimum and maximum values of the ADC. The input minimum is usually around 100 to 2000; the maximum is similarly less than full scale, sometimes significantly.

I'm not sure if I understand this. So far, I've been using the minimum and maximum value read my [in this case] Raspberry Pi Pico on the Analog Pin. How can I measure properly the minimum and maximum values of the potentiometer?

> Once instantiated with parameters that match your project, RangeSlicer properties shouldn't need to be changed. How are you setting it up in your project code?

For `in_min` and `in_max`, I read the minimum and maximum values of the Analog Input of the Pico. Then, I use those measured values and do not change them. However, I also considered to use a base values, and keep track of the minimum and maximum measured values. If they change significantly, I can recreate RangeSlicer with these new values.

`out_min` and `out_max`, are fixed values to `-127` and `127`. These are the values expected by the computer, the two potentiometers will represent an analog controller that provide values in the `X` and `Y` axis. 

`out_slice` is still a bit unclear for me. From you explanation, I feel like `1` would be a good value. I'm thinking about `out_slice` as the "jump" between one measure and its immediate next value. Please, correct me if I'm wrong on this.

You explanation about `hyst` is pretty clear. I'll use a value of `0.1`.

> The benefit of filtering, however, is that it can make the control "feel" smoother.

In my project the current noise is acceptable. Indeed, the gamepad is only used by my kids for playing TuxKart :-), but it is fun for me to give a new life to this device. I considered to implement a Kalman filter to remove the noise. I used it in the past to smooth the input signal of some sensors in robotic projects.

All in all, thanks again for the time you took. I'll implement the RangeSlicer in my project and let you know the results.

**Comment by CedarGroveStudios** [comment]
> How can measure properly the minimum and maximum values of the potentiometer?

Your existing calibration process should suffice. The potentiometer may drift over time (and with temperature), but the resultant change in the raw value should easily be accommodated by the slicer algorithm without having to recalibrate. The slicer algorithm considers any input value less than the specified minimum to be at the minimum; input values exceeding the maximum are limited to the specified maximum value.

> I'm thinking about out_slice as the "jump" between one measure and its immediate next value. Please, correct me if I'm wrong on this.

You're correct. The `out_slice` parameter is the increment between "stable" values. For MIDI and HID applications, an integer value of 1 should work nicely.

I think I understand better what your project needs now. You may want to try instantiation statements like:
`steering = RangeSlicer(in_min=200, in_max=64000, out_min=-127, out_max= 127, out_slice=1, hyst_factor=0.1, out_integer=True)`

`gear = RangeSlicer(in_min=250, in_max=63750, out_min=-127, out_max= 127, out_slice=1, hyst_factor=0.1, out_integer=True)`

and deliver the values with:

`steering.range_slicer(steering_wheel)`

`gear.range_slicer(gear_lever)`

When using RangeSlicer, the potentiometer input range should only have to be set once for each unique potentiometer. Any drift will probably be accommodated by the slicer algorithm.

That being said, the Kalman filter could be a good educational exercise and could have applications in other projects. I haven't seen it used in CircuitPython, so I don't know what performance issues it may present.

My [ShadowWatcher](https://github.com/CedarGroveStudios/CircuitPython_ShadowWatcher) gesture detector class uses a simple n-order finite impulse response (FIR) moving-average (boxcar) low-pass filter without the predictive feature of the Kalman filter. A unique function in the ShadowWatcher's FIR implementation is automatic detection of the analog input sampling speed -- needed to accurately calibrate the low-pass cutoff frequency.

**Comment by mmartinortiz** [comment]
I've updated my code based on your suggestions. The minimum and maximum value needed to be adjusted again, but now the output is quite stable, specially the minimum and maximum possible values for the gear and steering wheel (which, in this gamepad, are the most important, because you either brake hard, or go full gas :-) )

The Kalman filter is still something I want to try for educational purposes. Now, it is time for my kids to start the testing.

Again, thanks for the time you took in your explanations, I really appreciate it.
